- name: Download the sdist
  id: download-sdist
  run: |
    pip download --no-deps --no-binary=:all: ${GITHUB_EVENT_INPUTS_PACKAGE_NAME}==${GITHUB_EVENT_INPUTS_PACKAGE_VERSION}
    tarball=$(ls *.tar.gz)
    echo "tarball-hash=$(sha256sum "$tarball")" >> "$GITHUB_OUTPUT"
    tar --strip-components=1 -xvf  "$tarball"
    rm "$tarball"
