- name: Install build deps
  run: |
    curl -sSL https://raw.githubusercontent.com/${{ github.repository }}/$GITHUB_REF/build-requirements.txt \
      -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
      > build-requirements.txt
    python -m pip install --require-hashes -r build-requirements.txt
    rm build-requirements.txt
