- name: Install build deps
  env:
    GH_TOKEN: ${{ github.token }}
  run: |
    python -m pip install --require-hashes $(
      curl -sSL https://raw.githubusercontent.com/${{ github.repository }}/$GITHUB_REF/build-requirements.txt \
        -H "Authorization: token $GH_TOKEN"
    )
