- name: Make release
  env:
    GH_TOKEN: ${{ steps.app-token.outputs.token }}
    STEPS_DOWNLOAD_SDIST_OUTPUTS_TARBALL_HASH: ${{ steps.download-sdist.outputs.tarball-hash }}
  run: |
    gh release create \
        ${GITHUB_EVENT_INPUTS_PACKAGE_NAME}-${GITHUB_EVENT_INPUTS_PACKAGE_VERSION} \
        --title ${GITHUB_EVENT_INPUTS_PACKAGE_NAME}-${GITHUB_EVENT_INPUTS_PACKAGE_VERSION} \
        --notes "${STEPS_DOWNLOAD_SDIST_OUTPUTS_TARBALL_HASH}" \
        --draft \
        dist/*.whl
