- name: Report Success
  run: |
    gh issue comment ${GITHUB_EVENT_INPUTS_ISSUE_NUMBER} \
      --edit-last \
      --body ':white_check_mark: Ah! We have ${GITHUB_EVENT_INPUTS_PACKAGE_NAME}, yessir.'
    gh issue close ${GITHUB_EVENT_INPUTS_ISSUE_NUMBER}' \
      --reason completed
  env:
    GH_TOKEN: ${{ steps.app-token.outputs.token }}
    GITHUB_EVENT_INPUTS_ISSUE_NUMBER: ${{ github.event.inputs.issue_number }}
    GITHUB_EVENT_INPUTS_PACKAGE_NAME: ${{ github.event.inputs.package_name }}
