[project]
name = "keeping-it-wheel"
version = "0.1.0"
# The same as `ubuntu-24.04`
requires-python = "==3.12.3"
dependencies = []

[dependency-groups]
dev = ["cogapp", "httpx", "zizmor"]

[tool.uv.sources]
cogapp = { git = "https://github.com/thejcannon/cog" }
