name: Wheel Request
description: Request wheels be built.
title: "(Wheel Request)"
labels: ["wheel-request"]
body:
  - type: markdown
    attributes:
      value: |
        Good morning. Welcome to the National Cheese Emporium!

        What can I build for you?
  - type: input
    id: pypi-url
    attributes:
      label: PyPI URL
      description: What is the PyPI URL of the package+version?
      placeholder: ex https://pypi.org/project/httpx/0.28.1/
    validations:
      required: true
