# [[[cog
# import httpx
#
# UBUNTU_RUNNER = "ubuntu-24.04"
# WINDOWS_RUNNER = "windows-2025"
# MACOS_RUNNER = "macos-14"
#
# CI_BUILDWHEEL_INFO = httpx.get("https://api.github.com/repos/pypa/cibuildwheel/releases/latest").raise_for_status().json()
# ]]]
# [[[end]]]
name: Build and Upload Wheel

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "PyPI package name"
        required: true
      package_version:
        description: "Package version"
        required: true

permissions:
  contents: write

env:
  GH_REPO: ${{ github.repository }}

jobs:
  build_pure_wheel:
    name: Build pure Python wheel
    # [[[cog
    # cog.outl(f"runs-on: {UBUNTU_RUNNER}")
    # ]]]
    runs-on: ubuntu-24.04
    # [[[end]]]
    outputs:
      is_pure: ${{ steps.check_pure.outputs.is_pure }}
    steps:
      - name: Install build deps
        run: |
          curl -sSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/requirements.txt \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
          python -m pip install --require-hashes requirements.txt
          rm requirements.txt

      - name: Download the sdist
        shell: bash
        run: |
          pip download --no-deps --no-binary=:all: ${{ github.event.inputs.package_name }}==${{ github.event.inputs.package_version }}
          tarball=$(ls *.tar.gz)
          tar --strip-components=1 -xvf  "$tarball"
          rm "$tarball"

      - name: Build pure Python wheel
        shell: bash
        run: python -m build --wheel .

      - name: Check if wheel is pure Python
        id: check_pure
        run: |
          wheel_name=$(ls dist/*.whl)
          if [[ $wheel_name == *none-any.whl ]]; then
            echo "is_pure=true" >> $GITHUB_OUTPUT
          fi

      - name: Upload wheel to release
        if: steps.check_pure.outputs.is_pure == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }} dist/*.whl

  draft_release:
    name: Ensure Release
    # [[[cog
    # cog.outl(f"runs-on: {UBUNTU_RUNNER}")
    # ]]]
    runs-on: ubuntu-24.04
    # [[[end]]]
    needs: [build_pure_wheel]
    if: needs.build_pure_wheel.outputs.is_pure != 'true'
    steps:
      - name: Ensure draft release
        id: ensure_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if ! gh release view ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }} &>/dev/null; then
            gh release create ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }} --draft --title "${{ github.event.inputs.package_name }} ${{ github.event.inputs.package_version }}" --generate-notes
          fi

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: [draft_release]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # [[[cog
          # cog.outl(f"- {UBUNTU_RUNNER}")
          # cog.outl(f"- {WINDOWS_RUNNER}")
          # cog.outl(f"- {MACOS_RUNNER}")
          # ]]]
          - ubuntu-24.04
          - windows-2025
          - macos-14
          # [[[end]]]
    steps:
      - name: Download sdist
        shell: bash
        run: |
          pip download --no-deps --no-binary=:all: ${{ github.event.inputs.package_name }}==${{ github.event.inputs.package_version }}
          tarball=$(ls *.tar.gz)
          tar --strip-components=1 -xvf  "$tarball"
          rm "$tarball"

      - name: Build wheels
        # @TODO: Get SHA
        # [[[cog
        # cog.outl(f"# {CI_BUILDWHEEL_INFO['html_url']}")
        # cog.outl(f"uses: pypa/cibuildwheel@")
        # ]]]
        # https://github.com/pypa/cibuildwheel/releases/tag/v3.0.0
        uses: pypa/cibuildwheel@v3.0.0
        # [[[end]]]
        env:
          CIBW_REPAIR_WHEEL_COMMAND: ""
        with:
          package-dir: .
          output-dir: dist

      - name: Upload wheels to release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          for wheel in dist/*.whl; do
            gh release upload ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }} "$wheel" --clobber
          done

  publish_release:
    name: Publish Release
    needs: [build_wheels]
    # [[[cog
    # cog.outl(f"runs-on: {UBUNTU_RUNNER}")
    # ]]]
    runs-on: ubuntu-24.04
    # [[[end]]]
    steps:
      - name: Publish Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release edit ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }} --draft=false
