name: Build and Upload Wheel

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'PyPI package name'
        required: true
      package_version:
        description: 'Package version'
        required: true

permissions:
  contents: write

jobs:
  build_pure_wheel:
    name: Build pure Python wheel
    runs-on: ubuntu-latest
    outputs:
      is_pure: ${{ steps.check_pure.outputs.is_pure }}

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install pipx
      run: python -m pip install pipx

    - name: Download sdist
      run: |
        pip download --no-binary=:all: ${{ github.event.inputs.package_name }}==${{ github.event.inputs.package_version }}
        tar -xvf ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }}.tar.gz
        mv ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }}/* .
        rm ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }}.tar.gz

    - name: Build pure Python wheel
      run: pipx run build --wheel .

    - name: Check if wheel is pure Python
      id: check_pure
      run: |
        wheel_name=$(ls dist/*.whl)
        if [[ $wheel_name == *none-any.whl ]]; then
          echo "is_pure=true" >> $GITHUB_OUTPUT
        else
          echo "is_pure=false" >> $GITHUB_OUTPUT
        fi

    - name: Upload pure Python wheel
      if: steps.check_pure.outputs.is_pure == 'true'
      run: cd dist && gh release create ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }} *.whl
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: build_pure_wheel
    if: needs.build_pure_wheel.outputs.is_pure != 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Download sdist
      run: |
        pip download --no-binary=:all: ${{ github.event.inputs.package_name }}==${{ github.event.inputs.package_version }}
        tar -xvf ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }}.tar.gz
        mv ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }}/* .
        rm ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }}.tar.gz

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.19.1
      env:
        CIBW_REPAIR_WHEEL_COMMAND: ""
      with:
        package-dir: .
        output-dir: dist

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./dist/*.whl
