name: Build and Upload Wheel

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'PyPI package name'
        required: true
      package_version:
        description: 'Package version'
        required: true

permissions:
  contents: write

jobs:
  draft_release:
    name: Create or Get Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.ensure_release.outputs.id }}
    steps:
    - name: Ensure draft release
      id: ensure_release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        release_id=$(gh release view ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }} --json id -q .id 2>/dev/null || echo "")
        if [ -n "$release_id" ]; then
          echo "id=$release_id" >> $GITHUB_OUTPUT
        else
          release_id=$(gh release create ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }} --draft)
          echo "id=$release_id" >> $GITHUB_OUTPUT
        fi

  build_pure_wheel:
    name: Build pure Python wheel
    needs: draft_release
    runs-on: ubuntu-latest
    outputs:
      is_pure: ${{ steps.check_pure.outputs.is_pure }}

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install pipx
      run: python -m pip install pipx

    - name: Download sdist
      run: |
        pip download --no-binary=:all: ${{ github.event.inputs.package_name }}==${{ github.event.inputs.package_version }}
        tar -xvf ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }}.tar.gz
        mv ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }}/* .
        rm ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }}.tar.gz

    - name: Build pure Python wheel
      run: pipx run build --wheel .

    - name: Check if wheel is pure Python
      id: check_pure
      run: |
        wheel_name=$(ls dist/*.whl)
        if [[ $wheel_name == *none-any.whl ]]; then
          echo "is_pure=true" >> $GITHUB_OUTPUT
        else
          echo "is_pure=false" >> $GITHUB_OUTPUT
        fi

    - name: Upload wheel to release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release upload ${{ needs.draft_release.outputs.release_id }} dist/*.whl --clobber

    - name: Publish Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release edit ${{ needs.draft_release.outputs.release_id }} --draft=false

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: [draft_release, build_pure_wheel]
    if: needs.build_pure_wheel.outputs.is_pure != 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Download sdist
      run: |
        pip download --no-binary=:all: ${{ github.event.inputs.package_name }}==${{ github.event.inputs.package_version }}
        tar -xvf ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }}.tar.gz
        mv ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }}/* .
        rm ${{ github.event.inputs.package_name }}-${{ github.event.inputs.package_version }}.tar.gz

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.19.1
      env:
        CIBW_REPAIR_WHEEL_COMMAND: ""
      with:
        package-dir: .
        output-dir: dist

    - name: Upload wheels to release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release upload ${{ needs.draft_release.outputs.release_id }} dist/*.whl --clobber

  publish_release:
    name: Publish Release
    needs: [draft_release, build_wheels]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Publish Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release edit ${{ needs.draft_release.outputs.release_id }} --draft=false
